import {
    Award,
    BookOpen,
    Briefcase,
    CheckCircle,
    Code2,
    Compass,
    Flag,
    Footprints,
    GraduationCap,
    Brain,
    Leaf,
    Lightbulb,
    Palette,
    Rocket,
    Send,
    Sun,
    Target,
    Trophy,
    Users,
    Zap,
    type LucideIcon,
} from "lucide-react";
import type { TimelineIconName } from "@/lib/timeline-data";

// Data files store icon NAMES (plain strings survive the server → client
// boundary; component functions don't), and this resolves them.
export const TIMELINE_ICONS: Record<TimelineIconName, LucideIcon> = {
    Award,
    BookOpen,
    Briefcase,
    CheckCircle,
    Code2,
    Compass,
    Flag,
    Footprints,
    GraduationCap,
    Brain,
    Leaf,
    Lightbulb,
    Palette,
    Rocket,
    Send,
    Sun,
    Target,
    Trophy,
    Users,
    Zap,
};
