import {
    Award,
    BookOpen,
    Brain,
    Briefcase,
    CalendarCheck,
    CheckCircle,
    Code2,
    Compass,
    Flag,
    Footprints,
    GraduationCap,
    Leaf,
    Lightbulb,
    Mountain,
    Palette,
    PenLine,
    Rocket,
    Send,
    Smartphone,
    Sun,
    Target,
    Trophy,
    Users,
    Zap,
    type LucideIcon,
} from "lucide-react";
import type { TimelineIconName } from "@/lib/timeline-data";

// Data files store icon NAMES (plain strings survive the server → client
// boundary; component functions don't), and this resolves them. Typed as a
// full Record so adding a name to TimelineIconName without an icon here is a
// compile error, not a runtime crash.
export const TIMELINE_ICONS: Record<TimelineIconName, LucideIcon> = {
    Award,
    BookOpen,
    Brain,
    Briefcase,
    CalendarCheck,
    CheckCircle,
    Code2,
    Compass,
    Flag,
    Footprints,
    GraduationCap,
    Leaf,
    Lightbulb,
    Mountain,
    Palette,
    PenLine,
    Rocket,
    Send,
    Smartphone,
    Sun,
    Target,
    Trophy,
    Users,
    Zap,
};
